# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a62e05afc8cb7faf43f7cda8fd404568432235ae59e9d23d691fe3631a93d9aa2b9a6efe7af0d05573c5b7ee46cb570e33b9cce91676e421810b8720c1f926

test:
  secret_key_base: a4adeba4d65e7fdf469be1db219b01376700b7339a20dbcb228de1efb82c835ec022b258fa9b3c6771861acd1fd26395abf61bc3c029342c7ec7b54c15bd075b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
